image: python:3.7-slim

stages:
  - test
  - publish

.test:
  stage: test
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
  script:
    - poetry config virtualenvs.create false
    - poetry install --no-interaction --no-ansi
    - flake8
    - pytest --cov=kebab tests

3.6-slim: { extends: .test, image: 'python:3.6-slim' }
3.7-slim: { extends: .test, image: 'python:3.7-slim' }

publish:
  stage: publish
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - export VERSION=`grep -e "^version" pyproject.toml | tr -d '[" ]' | cut -d= -f2`
    - test "$CI_COMMIT_TAG" = "$VERSION"
  script:
    - poetry publish --build
  only:
    - tags
