image: python:3.7-slim

stages:
  - test
  - publish

test:
  stage: test
  before_script:
    - pip install poetry
  script:
    - poetry config virtualenvs.create false
    - poetry install --no-interaction --no-ansi
    - pytest tests

publish:
  stage: publish
  before_script:
    - pip install -y poetry
    - export VERSION=`grep -e "^version" pyproject.toml | tr -d '[" ]' | cut -d= -f2`
    - test $CI_COMMIT_TAG == $VERSION
  script:
    - poetry publish --build
  only:
    - tag
