logging:
  version: 1
  disable_existing_loggers: false
  handlers:
    console:
      class: logging.StreamHandler
      stream: ext://sys.stdout
  loggers:
    kebab.sources:
      level: INFO
    "":
      level: INFO
      handlers: [console]

