name: Lint and Test

# Reference to the two tutorials below:
# https://github.com/marketplace/actions/install-poetry-action
# https://testdriven.io/tips/810f9bb5-c9df-479d-baa4-290c7e0779f1/

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - master
  workflow_call:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: ${{ runner.os }}-pip
      - run: python -m pip install black flake8 flake8-black
      - run: |
          flake8 .

  build-n-test:
    needs: linting
    strategy:
      fail-fast: false
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.3.0
        with:
            poetry-version: 1.4.1
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi
      - name: Run pytest with coverage
        run: |
          poetry run pytest --cov=kebab --cov-report=xml tests/
          poetry run coverage report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
