name: Publish kebab to PyPI and TestPyPI

on:
  release:
    types:
      - created

jobs:
  publish:
    strategy:
      fail-fast: true
      matrix:
        python: ["3.7"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
            poetry-version: 1.4.1
      - name: Publish
        run: |
          poetry config pypi-token.pypi "${{ secrets.PYPI_TOKEN }}"
          export VERSION=`grep -e "^version" pyproject.toml | tr -d '[" ]' | cut -d= -f2`
          test "$GITHUB_REF_NAME" = "$VERSION"
          poetry publish --build
