name: Publish kebab to PyPI and TestPyPI

on:
  release:
    types:
      - created

jobs:
  publish:
    strategy:
      fail-fast: true
      matrix:
        python: ["3.7"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Ensure version
        run: |
          export VERSION=`grep -e "^version" pyproject.toml | tr -d '[" ]' | cut -d= -f2`
          test "$GITHUB_REF_NAME" = "$VERSION"
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.17
        with:
          python-version: ${{ matrix.python }}
          poetry-version: 1.4.1
          pypi_token: ${{ secrets.PYPI_TOKEN }}
